export interface Service {
  name: string;
  description: string;
  companyTypes?: ("MEI" | "LTDA" | "EI" | "Todos")[];
  regions?: string[];
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  description: string;
  services: Service[];
}

export const servicesData: Category[] = [
  {
    id: "limpezas",
    name: "LIMPEZAS",
    icon: "Sparkles",
    description: "Serviços de limpeza residencial, comercial e especializada",
    services: [
      { name: "Limpeza Residencial", description: "Limpeza profunda de toda residência" },
      { name: "Limpeza Pós-Obra", description: "Remoção de resíduos e sujeira de obra" },
      { name: "Limpeza Comercial", description: "Higienização de ambientes corporativos" },
      { name: "Limpeza Industrial", description: "Limpeza especializada para indústrias" },
      { name: "Limpeza de Estofados", description: "Higienização profunda de sofás e poltronas" },
      { name: "Limpeza de Carpetes", description: "Limpeza profissional de carpetes" },
      { name: "Limpeza de Áreas Externas", description: "Limpeza de quintais e áreas abertas" },
      { name: "Limpeza de Vidros", description: "Limpeza de janelas e fachadas de vidro" },
      { name: "Limpeza de Fachadas", description: "Limpeza de fachadas prediais" },
      { name: "Limpeza de Piscinas", description: "Tratamento e limpeza de piscinas" },
      { name: "Limpeza de Toldos", description: "Lavagem e conservação de toldos" },
    ],
  },
  {
    id: "manutencao",
    name: "MANUTENÇÃO",
    icon: "Wrench",
    description: "Serviços de manutenção preventiva e corretiva",
    services: [
      { name: "Manutenção de Ar-Condicionado", description: "Limpeza e manutenção de ar-condicionado" },
      { name: "Manutenção de Piscinas (técnica)", description: "Tratamento químico e manutenção técnica" },
      { name: "Manutenção Elétrica", description: "Reparos e manutenção em sistemas elétricos" },
      { name: "Manutenção Hidráulica", description: "Reparos em encanamentos e instalações" },
      { name: "Manutenção de Portões", description: "Manutenção de portões eletrônicos e manuais" },
      { name: "Manutenção de Bombas", description: "Manutenção de bombas d'água" },
      { name: "Manutenção de Câmeras (CFTV)", description: "Manutenção de sistemas de vigilância" },
      { name: "Manutenção de Internet / Wi-Fi", description: "Configuração e reparo de redes" },
      { name: "Manutenção de Jardim (Corte e Poda)", description: "Cuidados com jardins e plantas" },
      { name: "Técnico de Refrigeração", description: "Manutenção de sistemas de refrigeração" },
    ],
  },
  {
    id: "reparo",
    name: "REPARO",
    icon: "Wrench",
    description: "Reparos domésticos e pequenos consertos",
    services: [
      { name: "Reparos Domésticos", description: "Consertos gerais em residências" },
      { name: "Pequenos Reparos", description: "Consertos rápidos e emergenciais" },
      { name: "Troca de Peças", description: "Substituição de componentes defeituosos" },
      { name: "Ajustes de Portas", description: "Ajustes e alinhamento de portas" },
      { name: "Ajustes de Gavetas", description: "Correção de gavetas e móveis" },
      { name: "Ajustes de Dobradiças", description: "Troca e ajuste de dobradiças" },
      { name: "Consertos Elétricos Simples", description: "Reparos elétricos básicos" },
      { name: "Consertos Hidráulicos Simples", description: "Reparos hidráulicos básicos" },
      { name: "Correção de Pequenas Infiltrações", description: "Tratamento de vazamentos" },
      { name: "Reparo de Pisos", description: "Conserto de pisos danificados" },
      { name: "Reparo de Azulejos Soltos", description: "Fixação de azulejos" },
    ],
  },
  {
    id: "construcao",
    name: "CONSTRUÇÃO",
    icon: "HardHat",
    description: "Serviços de construção, reforma e acabamento",
    services: [
      { name: "Pintura", description: "Pintura residencial e comercial" },
      { name: "Instalação de Móveis", description: "Montagem de móveis planejados" },
      { name: "Marcenaria", description: "Móveis sob medida em madeira" },
      { name: "Serralheria", description: "Trabalhos em metal e ferro" },
      { name: "Telhados", description: "Instalação e manutenção de telhados" },
      { name: "Forros", description: "Instalação de forros de gesso e PVC" },
      { name: "Pisos", description: "Instalação de pisos e revestimentos" },
      { name: "Reformas Gerais", description: "Reformas completas de ambientes" },
      { name: "Ampliações", description: "Ampliação de construções" },
      { name: "Instalação de Drywall", description: "Paredes em drywall" },
      { name: "Instalação de Gesso", description: "Trabalhos em gesso" },
      { name: "Assentamento de Porcelanato", description: "Instalação de porcelanato" },
      { name: "Construção de Fachadas", description: "Construção e reforma de fachadas" },
    ],
  },
  {
    id: "instalacoes",
    name: "INSTALAÇÕES",
    icon: "Settings",
    description: "Instalações de segurança, redes e infraestrutura",
    services: [
      { name: "Instalação de Portão Eletrônico", description: "Instalação de portões automáticos" },
      { name: "Instalação de Motor de Portão", description: "Motorização de portões" },
      { name: "Instalação de Cerca Elétrica", description: "Sistema de segurança perimetral" },
      { name: "Instalação de Interfone", description: "Sistema de comunicação residencial" },
      { name: "Instalação de Vídeo Porteiro", description: "Vídeo porteiro digital" },
      { name: "Instalação de Câmeras (CFTV)", description: "Sistema de vigilância" },
      { name: "Instalação de Alarmes", description: "Sistemas de alarme" },
      { name: "Instalação de Sensores", description: "Sensores de movimento e presença" },
      { name: "Instalação de Fechadura Eletrônica", description: "Fechaduras inteligentes" },
      { name: "Instalação de Redes / Internet", description: "Cabeamento e redes" },
      { name: "Instalação de Iluminação", description: "Sistemas de iluminação" },
      { name: "Instalação de Painel Solar", description: "Energia solar fotovoltaica" },
      { name: "Instalação de Ventiladores / Exaustores", description: "Ventilação e exaustão" },
      { name: "Instalação de Sistemas de Irrigação", description: "Irrigação automatizada" },
      { name: "Instalação de Paisagismo / Cercas Vivas", description: "Paisagismo e jardinagem" },
      { name: "Instalador de Antenas e Receptores", description: "Antenas e sistemas de TV" },
      { name: "Chaveiro", description: "Serviços de chaveiro" },
    ],
  },
  {
    id: "beleza-estetica",
    name: "BELEZA & ESTÉTICA",
    icon: "Sparkles",
    description: "Serviços de beleza, estética e cuidados pessoais",
    services: [
      { name: "Corte Feminino", description: "Cortes modernos e clássicos femininos" },
      { name: "Corte Masculino", description: "Cortes masculinos" },
      { name: "Escova", description: "Escova modeladora profissional" },
      { name: "Penteado", description: "Penteados para eventos" },
      { name: "Tratamento Capilar Feminino", description: "Hidratação e reconstrução capilar" },
      { name: "Tratamento Capilar Masculino", description: "Tratamentos capilares masculinos" },
      { name: "Barba", description: "Corte e design de barba" },
      { name: "Design de Barba", description: "Modelagem profissional de barba" },
      { name: "Manicure e Pedicure", description: "Cuidados com unhas" },
      { name: "Alongamento de Unhas", description: "Aplicação de alongamento" },
      { name: "Design de Sobrancelhas", description: "Modelagem e design feminino" },
      { name: "Design de Sobrancelhas Masculino", description: "Design de sobrancelhas masculino" },
      { name: "Henna", description: "Aplicação de henna" },
      { name: "Extensão de Cílios", description: "Aplicação de cílios postiços" },
      { name: "Lifting", description: "Lifting de cílios" },
      { name: "Manutenção de Cílios", description: "Manutenção de extensões" },
      { name: "Maquiagem", description: "Maquiagem profissional" },
      { name: "Limpeza de Pele", description: "Limpeza profunda facial" },
      { name: "Peeling", description: "Renovação celular" },
      { name: "Massagem Relaxante Feminina", description: "Massagem relaxante" },
      { name: "Massagem Relaxante Masculina", description: "Massagem masculina" },
      { name: "Drenagem", description: "Drenagem linfática" },
      { name: "Bronzeamento Artificial", description: "Bronzeamento em cabine" },
      { name: "Depilação Feminina", description: "Depilação com cera" },
      { name: "Depilação Masculina", description: "Depilação masculina" },
      { name: "Micropigmentação Labial", description: "Pigmentação de lábios" },
      { name: "Micropigmentação de Sobrancelhas", description: "Micropigmentação" },
      { name: "Laser de CO2 fracionado", description: "Tratamento a laser" },
      { name: "Depilação a Laser", description: "Remoção definitiva de pelos" },
    ],
  },
  {
    id: "juridico",
    name: "JURÍDICO",
    icon: "Scale",
    description: "Serviços jurídicos especializados",
    services: [
      { name: "Advogado Criminal", description: "Defesa criminal" },
      { name: "Advogado de Família", description: "Divórcios e inventários" },
      { name: "Advogado Trabalhista", description: "Direito do trabalho" },
      { name: "Advogado Cível", description: "Direito civil" },
      { name: "Advogado Empresarial", description: "Direito empresarial" },
      { name: "Advogado Previdenciário", description: "Direito previdenciário" },
      { name: "Advogado Tributário", description: "Direito tributário" },
      { name: "Advogado Imobiliário", description: "Direito imobiliário" },
      { name: "Advogado Ambiental", description: "Direito ambiental" },
      { name: "Advogado Consumerista", description: "Direito do consumidor" },
    ],
  },
  {
    id: "consultorias",
    name: "CONSULTORIAS",
    icon: "Briefcase",
    description: "Consultorias especializadas em diversas áreas",
    services: [
      { name: "Consultoria de Marketing", description: "Estratégias de marketing" },
      { name: "Consultoria de Gestão", description: "Gestão empresarial" },
      { name: "Consultoria de Recursos Humanos", description: "Gestão de pessoas" },
      { name: "Consultoria de Vendas", description: "Estratégias de vendas" },
      { name: "Consultoria de Imagem & Estilo", description: "Personal styling" },
      { name: "Consultoria de Organização", description: "Personal organizer" },
      { name: "Consultoria de Marketing Digital", description: "Estratégias digitais" },
      { name: "Consultoria Agropecuária", description: "Gestão rural e agrícola" },
      { name: "Consultoria de Segurança Eletrônica", description: "Segurança patrimonial" },
      { name: "Consultoria de Branding", description: "Gestão de marca" },
      { name: "Consultoria de Emagrecimento", description: "Planejamento nutricional" },
      { name: "Personal Shopper", description: "Consultoria de compras" },
      { name: "Consultoria de Viagem", description: "Planejamento de viagens" },
      { name: "Secretariado Virtual", description: "Assistência administrativa remota" },
    ],
  },
  {
    id: "saude-bem-estar",
    name: "SAÚDE & BEM-ESTAR",
    icon: "Heart",
    description: "Serviços de saúde e bem-estar",
    services: [
      { name: "Médico", description: "Consultas médicas domiciliares" },
      { name: "Enfermagem", description: "Serviços de enfermagem" },
      { name: "Fisioterapia", description: "Tratamentos fisioterápicos" },
      { name: "Psicológico", description: "Psicoterapia e acompanhamento" },
      { name: "Terapias Alternativas", description: "Acupuntura, reiki e outras terapias" },
      { name: "Nutrição", description: "Consultoria nutricional" },
    ],
  },
  {
    id: "educacao",
    name: "EDUCAÇÃO",
    icon: "GraduationCap",
    description: "Serviços educacionais e cursos",
    services: [
      { name: "Reforço Escolar", description: "Aulas particulares" },
      { name: "Alfabetização", description: "Alfabetização de crianças e adultos" },
      { name: "Aulas de Inglês", description: "Conversação e gramática" },
      { name: "Aulas de Violão", description: "Aulas de violão" },
      { name: "Aulas de Piano / Teclado", description: "Aulas de piano e teclado" },
      { name: "Desenho", description: "Artes plásticas e desenho" },
      { name: "Informática Básica", description: "Introdução ao computador" },
      { name: "Informática Avançada", description: "Programação e tecnologia" },
      { name: "Redação", description: "Técnicas de redação" },
      { name: "Preparatório para Concursos", description: "Preparação para concursos públicos" },
      { name: "Preparatório para Vestibulares", description: "Preparação para ENEM e vestibulares" },
    ],
  },
  {
    id: "automotivos",
    name: "AUTOMOTIVOS",
    icon: "Car",
    description: "Serviços automotivos",
    services: [
      { name: "Lavagem e Higienização", description: "Lavagem completa e higienização interna" },
      { name: "Polimento", description: "Polimento de pintura" },
      { name: "Mecânica Rápida", description: "Serviços mecânicos básicos" },
      { name: "Troca de Óleo", description: "Troca de óleo e filtros" },
      { name: "Guincho 24h", description: "Reboque e socorro veicular" },
      { name: "Serviços para Motos", description: "Manutenção de motocicletas" },
      { name: "Chaveiro Automotivo", description: "Cópias de chaves e abertura de veículos" },
    ],
  },
  {
    id: "pets",
    name: "PETS",
    icon: "Dog",
    description: "Serviços para animais de estimação",
    services: [
      { name: "Banho e Tosa", description: "Higienização e corte" },
      { name: "Hidratação de Pelagem", description: "Tratamento de pelos" },
      { name: "Desembolo", description: "Remoção de nós e pelos embaraçados" },
      { name: "Tosa Higiênica", description: "Higiene específica" },
      { name: "Corte de Unhas", description: "Corte de unhas pet" },
      { name: "Limpeza de Ouvidos", description: "Higienização auricular" },
      { name: "Controle de Pulgas e Carrapatos", description: "Tratamento antiparasitário" },
      { name: "Veterinário", description: "Consultas veterinárias" },
      { name: "Vacinação", description: "Imunização de pets" },
      { name: "Consultas Preventivas", description: "Check-ups veterinários" },
      { name: "Atendimento Domiciliar", description: "Veterinário em casa" },
      { name: "Aplicação de Medicamentos", description: "Medicação veterinária" },
      { name: "Curativos", description: "Tratamento de ferimentos" },
      { name: "Primeiros Socorros Pet", description: "Atendimento emergencial" },
      { name: "Pet Sitter", description: "Cuidador de pets" },
      { name: "Dog Walker", description: "Passeio profissional" },
      { name: "Acompanhamento em Consultas", description: "Acompanhante para pets" },
      { name: "Adestramento Básico", description: "Comandos essenciais" },
      { name: "Adestramento Avançado", description: "Treinamento especializado" },
      { name: "Correção Comportamental", description: "Modificação de comportamento" },
      { name: "Hospedagem Pet", description: "Hotel para pets" },
      { name: "Creche Pet", description: "Day care para pets" },
      { name: "Transporte Pet", description: "Transporte seguro de animais" },
      { name: "Transporte para Veterinário", description: "Transporte para consultas" },
      { name: "Transporte para Viagens", description: "Transporte para viagens" },
      { name: "Fotografia Pet", description: "Ensaios fotográficos de pets" },
      { name: "Ensaio Temático", description: "Fotos temáticas de pets" },
      { name: "Festas Pet", description: "Eventos para animais" },
    ],
  },
  {
    id: "eventos",
    name: "EVENTOS",
    icon: "PartyPopper",
    description: "Serviços para festas e eventos",
    services: [
      { name: "Fotógrafo", description: "Cobertura fotográfica de eventos" },
      { name: "Filmagem", description: "Vídeo profissional de eventos" },
      { name: "Buffet", description: "Serviço de alimentação" },
      { name: "Bartender", description: "Drinks profissionais" },
      { name: "Churrasqueiro", description: "Serviço especializado de churrasco" },
      { name: "Decoração", description: "Ambientação temática" },
      { name: "Cerimonial", description: "Organização e coordenação" },
      { name: "Música", description: "DJ e música ao vivo" },
      { name: "Recreação", description: "Animação e entretenimento" },
    ],
  },
  {
    id: "criativos-digitais",
    name: "CRIATIVOS & DIGITAIS",
    icon: "Palette",
    description: "Serviços criativos e de marketing digital",
    services: [
      { name: "Design Gráfico", description: "Criação de peças gráficas" },
      { name: "Identidade Visual", description: "Logo e manual de marca" },
      { name: "Social Media", description: "Criação de conteúdo para redes" },
      { name: "Gestão de Redes Sociais", description: "Gerenciamento de mídias sociais" },
      { name: "Tráfego Pago", description: "Anúncios online e campanhas" },
      { name: "Desenvolvimento de Sites", description: "Criação de websites" },
      { name: "E-commerce", description: "Lojas virtuais" },
    ],
  },
  {
    id: "transporte",
    name: "TRANSPORTE",
    icon: "Truck",
    description: "Serviços de transporte e logística",
    services: [
      { name: "Motorista Particular", description: "Transporte executivo" },
      { name: "Transporte Executivo", description: "Transporte corporativo" },
      { name: "Viagens", description: "Transporte para viagens" },
      { name: "Fretes", description: "Transporte de cargas" },
      { name: "Carretos", description: "Fretes pequenos" },
      { name: "Mudanças", description: "Transporte de mudanças" },
      { name: "Entregas Expressas", description: "Delivery rápido" },
      { name: "Transporte Escolar", description: "Transporte de estudantes" },
      { name: "Guincho", description: "Reboque 24h" },
    ],
  },
  {
    id: "agricultura-pecuaria",
    name: "AGRICULTURA & PECUÁRIA",
    icon: "Tractor",
    description: "Serviços agrícolas, pecuários e tecnologia rural",
    services: [
      // Operações Agrícolas
      { name: "Plantio", description: "Preparo e plantio de culturas" },
      { name: "Colheita", description: "Colheita mecanizada" },
      { name: "Aragem", description: "Preparo do solo com arado" },
      { name: "Gradeação", description: "Nivelamento do solo" },
      { name: "Aplicação de Calcário", description: "Correção de acidez do solo" },
      { name: "Aplicação de Adubo", description: "Fertilização do solo" },
      { name: "Aplicação de Defensivos", description: "Controle de pragas e doenças" },
      { name: "Formação de Pastagem", description: "Implantação de pastagens" },
      { name: "Coleta de Solo", description: "Amostragem de solo" },
      { name: "Análise de Solo", description: "Análise laboratorial" },
      { name: "Correção de Solo", description: "Correção nutricional" },
      // Tecnologia Rural
      { name: "Medição de Terra por Drone", description: "Levantamento topográfico com drone" },
      { name: "Mapeamento Agrícola por Drone", description: "Mapeamento de áreas agrícolas" },
      { name: "Monitoramento de Lavoura por Drone", description: "Monitoramento aéreo de plantações" },
      { name: "Pulverização por Drone", description: "Aplicação aérea de defensivos" },
      { name: "Contagem de Plantas por Drone / IA", description: "Contagem automatizada" },
      { name: "Contagem de Gado por Drone", description: "Contagem de rebanho" },
      { name: "Inspeção de Cercas por Drone", description: "Vistoria aérea de cercas" },
      { name: "Georreferenciamento Rural (GPS/RTK)", description: "Mapeamento georreferenciado" },
      { name: "Cadastro Ambiental Rural (CAR)", description: "Regularização ambiental" },
      { name: "Monitoramento de Pastagens (NDVI)", description: "Análise de qualidade de pastagens" },
      { name: "Agricultura de Precisão", description: "Tecnologia aplicada à agricultura" },
      { name: "Sensoriamento Remoto", description: "Monitoramento via satélite" },
      { name: "Topografia Rural com RTK", description: "Topografia de alta precisão" },
      // Pecuária
      { name: "Transporte de Gado", description: "Transporte de animais" },
      { name: "Pesagem e Manejo de Gado", description: "Manejo de rebanho" },
      { name: "Castração de Bovinos", description: "Castração técnica" },
      { name: "Vacinação de Bovinos", description: "Imunização de rebanho" },
      { name: "Inseminação Artificial", description: "Reprodução assistida" },
      // Construção Rural
      { name: "Construção Rural", description: "Construções em propriedades rurais" },
      { name: "Construção de Galpões", description: "Barracões e galpões rurais" },
      { name: "Construção de Currais", description: "Estruturas para manejo" },
      // Manutenções Rurais
      { name: "Manutenção de Máquinas Agrícolas", description: "Manutenção de tratores e implementos" },
      { name: "Manutenção de Cercas", description: "Reparos em cercas" },
      { name: "Manutenção de Bebedouros", description: "Manutenção de sistemas de água" },
      { name: "Instalação de Cochos", description: "Instalação de estruturas de alimentação" },
      { name: "Soldagem Rural", description: "Soldagem e reparos metálicos" },
      { name: "Cercas Elétricas Rurais", description: "Instalação de cercas eletrificadas" },
      // Máquinas Pesadas
      { name: "Serviços com Retroescavadeira", description: "Escavação e terraplenagem" },
      { name: "Serviços com Escavadeira Hidráulica", description: "Movimentação de terra" },
      { name: "Serviços com Trator", description: "Operações com trator" },
      // Ambiental Rural
      { name: "Roçagem e Limpeza de Área", description: "Limpeza de terrenos" },
      { name: "Limpeza de Represas e Açudes", description: "Manutenção de reservatórios" },
      { name: "Abertura e Limpeza de Estradas Rurais", description: "Manutenção de vias rurais" },
      { name: "Serviços com Motosserra", description: "Corte e poda com motosserra" },
      { name: "Corte de Árvores", description: "Remoção de árvores" },
      { name: "Desgalhamento", description: "Poda e limpeza de árvores" },
      // Irrigação Rural
      { name: "Instalação de Sistema de Irrigação Rural", description: "Sistemas de irrigação" },
    ],
  },
  {
    id: "lazer-turismo",
    name: "LAZER & TURISMO",
    icon: "Plane",
    description: "Serviços de turismo e lazer",
    services: [
      { name: "Passeios Urbanos", description: "City tours e passeios guiados" },
      { name: "Passeios Ecológicos", description: "Trilhas e ecoturismo" },
      { name: "Turismo Rural", description: "Experiências em fazendas" },
      { name: "Turismo de Pesca", description: "Pescarias guiadas" },
      { name: "Locação de Equipamentos", description: "Aluguel de equipamentos de lazer" },
      { name: "Turismo de Aventura", description: "Esportes radicais e aventura" },
      { name: "Roteiros Culturais", description: "Tours culturais e históricos" },
    ],
  },
  {
    id: "esportivos",
    name: "ESPORTIVOS",
    icon: "Dumbbell",
    description: "Serviços esportivos e fitness",
    services: [
      { name: "Treinamento Funcional", description: "Exercícios funcionais" },
      { name: "Aulas de Dança", description: "Aulas de diversos estilos de dança" },
      { name: "Yoga & Meditação", description: "Práticas de bem-estar" },
      { name: "Reabilitação Física", description: "Recuperação física" },
      { name: "Treinos em Grupo", description: "Atividades coletivas" },
      { name: "Treinador de Goleiro", description: "Treinamento especializado de goleiros" },
      { name: "Pilates", description: "Método pilates" },
      { name: "Artes marciais", description: "Aulas de artes marciais" },
      { name: "Escolinha de futebol", description: "Iniciação ao futebol" },
      { name: "Beach Tennis", description: "Aulas de beach tennis" },
      { name: "Padel", description: "Aulas de padel" },
      { name: "Hidroginástica", description: "Ginástica aquática" },
      { name: "Cross Training", description: "Treino intensivo" },
      { name: "Natação", description: "Aulas de natação" },
    ],
  },
  {
    id: "cuidado-acompanhamento",
    name: "CUIDADO & ACOMPANHAMENTO HUMANO",
    icon: "HeartHandshake",
    description: "Cuidados e acompanhamento de pessoas",
    services: [
      { name: "Babá", description: "Cuidados infantis" },
      { name: "Cuidador de Idosos", description: "Assistência especializada a idosos" },
      { name: "Cuidador de Idosos Acamados", description: "Cuidados para idosos acamados" },
      { name: "Cuidador de Pessoas com Deficiência", description: "Assistência especializada" },
      { name: "Acompanhante de Idosos", description: "Companhia para idosos" },
      { name: "Acompanhante para Consultas / Exames", description: "Acompanhamento em consultas" },
      { name: "Auxílio na Rotina", description: "Ajuda nas atividades diárias" },
      { name: "Monitor de Crianças", description: "Supervisão de crianças" },
      { name: "Acompanhante Escolar", description: "Acompanhamento no transporte escolar" },
    ],
  },
  {
    id: "arquitetura-engenharia",
    name: "ARQUITETURA, ENGENHARIA & DESIGN",
    icon: "Building2",
    description: "Projetos arquitetônicos, engenharia e design de interiores",
    services: [
      { name: "Projeto Arquitetônico", description: "Projetos arquitetônicos completos" },
      { name: "Projeto de Fachada", description: "Design de fachadas" },
      { name: "Projeto de Reforma", description: "Projetos de reforma e adequação" },
      { name: "Projeto de Ampliação", description: "Projetos de ampliação" },
      { name: "Memorial Descritivo", description: "Documentação técnica" },
      { name: "Aprovação de Projeto na Prefeitura", description: "Regularização de projetos" },
      { name: "Regularização de Imóvel", description: "Regularização documental" },
      { name: "Laudo Técnico", description: "Laudos técnicos diversos" },
      { name: "Engenharia Civil", description: "Projetos de engenharia civil" },
      { name: "Engenharia Elétrica", description: "Projetos elétricos" },
      { name: "Engenharia Hidráulica", description: "Projetos hidráulicos" },
      { name: "Laudo de Engenharia", description: "Laudos técnicos de engenharia" },
      { name: "ART (Anotação de Responsabilidade Técnica)", description: "Registro profissional" },
      { name: "Cálculo Estrutural", description: "Dimensionamento estrutural" },
      { name: "Vistoria Técnica", description: "Inspeções técnicas" },
      { name: "Inspeção Predial", description: "Vistoria de edificações" },
      { name: "Gerenciamento de Obras", description: "Gestão de construções" },
      { name: "Design de Interiores Residencial", description: "Projetos residenciais" },
      { name: "Design de Interiores Comercial", description: "Projetos comerciais" },
      { name: "Consultoria de Ambientes", description: "Consultoria de decoração" },
      { name: "Projeto de Mobiliário", description: "Design de móveis" },
      { name: "Projeto de Iluminação", description: "Iluminação técnica e decorativa" },
      { name: "Planejamento Funcional de Espaços", description: "Otimização de espaços" },
      { name: "Ambientação & Decoração", description: "Decoração de ambientes" },
    ],
  },
];

export const getCategoryById = (id: string): Category | undefined => {
  return servicesData.find(cat => cat.id === id);
};

export const getAllServices = () => {
  return servicesData.flatMap(category =>
    category.services.map(service => ({
      ...service,
      category: category.name,
      categoryId: category.id,
    }))
  );
};
